//ROS typedefs
#include "ros/ros.h"
#include <sensor_msgs/JointState.h>
#include <control_msgs/JointTrajectoryControllerState.h>

/* protected region user include files on begin */
/* protected region user include files end */

class kr16_node_config
{
public:
		std::string robot_ip_address;
		std::string robot_description;
		int robot_port;

};

class kr16_node_data
{
// autogenerated: don't touch this class
public:
//input data
  
	
//output data
    	sensor_msgs::JointState out_joint_states;
    	control_msgs::JointTrajectoryControllerState out_state;
 

};

class kr16_node_impl
{
	/* protected region user member variables on begin */
	/* protected region user member variables end */

public:
    kr16_node_impl() 
    {
        /* protected region user constructor on begin */
		/* protected region user constructor end */
    }
    void configure(kr16_node_config config) 
    {
        /* protected region user configure on begin */
		/* protected region user configure end */
    }
    void update(kr16_node_data &data, kr16_node_config config)
    {
        /* protected region user update on begin */
		/* protected region user update end */
    }

    
    void callback_follow_joint_trajectory_action_(const control_msgs::FollowJointTrajectoryGoalConstPtr &goal, actionlib::SimpleActionServer<control_msgs::FollowJointTrajectoryAction> *as_)
    {
    	/* protected region user implementation of action callback for follow_joint_trajectory_action on begin */
		/* protected region user implementation of action callback for follow_joint_trajectory_action end */
    
    }
    


    
    /* protected region user additional functions on begin */
	/* protected region user additional functions end */
    
};
