##############################
#       This Action is       #
#      for Testing only      #
##############################

# Define the goal
string output
---
# Define the result

---
# Define a feedback message


