//ROS typedefs
#include "ros/ros.h"
#include <control_msgs/JointTrajectoryControllerState.h>

/* protected region user include files on begin */
/* protected region user include files end */

class kr16_test_client_config
{
public:
		std::string joint_position_1;
		std::string joint_position_2;

};

class kr16_test_client_data
{
// autogenerated: don't touch this class
public:
//input data
    	control_msgs::JointTrajectoryControllerState in_state;
  
	
//output data
 

};

class kr16_test_client_impl
{
	/* protected region user member variables on begin */
	/* protected region user member variables end */

public:
    kr16_test_client_impl() 
    {
        /* protected region user constructor on begin */
		/* protected region user constructor end */
    }
    void configure(kr16_test_client_config config) 
    {
        /* protected region user configure on begin */
		/* protected region user configure end */
    }
    void update(kr16_test_client_data &data, kr16_test_client_config config)
    {
        /* protected region user update on begin */
		/* protected region user update end */
    }

    


    
    /* protected region user additional functions on begin */
	/* protected region user additional functions end */
    
};
