joint_names: ['arm_shoulder_pan_joint', 'arm_shoulder_lift_joint', 'arm_elbow_joint', 'arm_wrist_1_joint', 'arm_wrist_2_joint', 'arm_wrist_3_joint']
action_name: "/arm_controller/follow_joint_trajectory"

home: [[3.14, -1.5708, -1.5708, -1.5708, 1.5708, 0]]
